### ISSUE TITLE
/usr/lib64/nagios/plugins/check_storm.py

### ISSUE THREAD

**Issue by Strijd** [keedio/nagios-hadoop#9]
Hi 
I'm using centos7 with storm installed:
yum install python-storm : no such file 
I downloaded  python-storm-0.20-2.1.3.x86_64.rpm and installed it successfully, yet when I run the script i get : 
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_storm.py", line 23, in <module>
    import stormStatus
  File "/usr/lib64/nagios/plugins/stormStatus.py", line 28, in <module>
    from storm import Nimbus
ImportError: cannot import name Nimbus

**Comment by jucaf** [comment]
You can try this rpm http://repo.keedio.org/openbus/1.2/rpm/python-storm-0.9.2-openbus_1.2.0.x86_64.rpm, or also you can copy Nimbus.py from storm sources https://github.com/apache/storm/tree/master/storm-core/src/py and paste at /usr/lib64/python2.6/site-packages/

**Comment by Strijd** [comment]
Thanks , that is what I did. Working. Thank you for the reply

**Comment by Strijd** [comment]
There are some issues : 
/usr/lib64/nagios/plugins/check_storm.py  --nimbus_serv x.x.x.x:
oot@noc-stormnode1 nrpe.d]# /usr/lib64/nagios/plugins/check_storm.py  --nimbus_serv 10.204.45.242 

output:

UNKNOWN: TypeError: unhashable instance
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 38, in wrapper
    return func(*args, **kwds)
  File "/usr/lib64/nagios/plugins/check_storm.py", line 69, in main
    check = nagiosplugin.Check(StormTopology(args),
  File "/usr/lib64/nagios/plugins/stormStatus.py", line 46, in __init__
    self.get_topology_status(topology)
  File "/usr/lib64/nagios/plugins/stormStatus.py", line 75, in get_topology_status
    executors=client.getTopologyInfo(self.topologies[topology]['id']).executors
  File "/usr/lib64/python2.7/site-packages/storm/Nimbus.py", line 586, in getTopologyInfo
    return self.recv_getTopologyInfo()
  File "/usr/lib64/python2.7/site-packages/storm/Nimbus.py", line 604, in recv_getTopologyInfo
    result.read(self._iprot)
  File "/usr/lib64/python2.7/site-packages/storm/Nimbus.py", line 2832, in read
    self.success.read(iprot)
  File "/usr/lib64/python2.7/site-packages/storm/ttypes.py", line 2726, in read
    _elem265.read(iprot)
  File "/usr/lib64/python2.7/site-packages/storm/ttypes.py", line 2602, in read
    self.stats.read(iprot)
  File "/usr/lib64/python2.7/site-packages/storm/ttypes.py", line 2393, in read
    self.specific.read(iprot)
  File "/usr/lib64/python2.7/site-packages/storm/ttypes.py", line 2282, in read
    self.bolt.read(iprot)
  File "/usr/lib64/python2.7/site-packages/storm/ttypes.py", line 1981, in read
    _val128[_key134] = _val135
TypeError: unhashable instance

**Comment by jucaf** [comment]
Are you using storm 0.9.2? if you are using another version should take storm python class from source code.

I didn't try with python2.7, maybe it's a issue with it.

**Comment by Strijd** [comment]
0.9.2

**Comment by jucaf** [comment]
sorry, but I can't find the problem. You could try printing some debug information.
